from pathlib import Path

path = Path('src/lib/daily-briefing-data.ts')
text = path.read_text()

text = text.replace(
'''  kind: "art_studio" | "lesson" | "carry_over";''',
'''  kind: "art_studio" | "lesson" | "carry_over" | "tomorrow_prep" | "tomorrow_worksheet" | "tomorrow_blocker";'''
)

marker = '''  const events: DailyEvent[] = [\n'''
insert = '''  const tomorrowStart = `${nextDate}T00:00:00`;\n  const tomorrowEnd = `${addDays(nextDate, 1)}T00:00:00`;\n  const [tomorrowLessonsResult, tomorrowCalendarResult, tomorrowSystemResult] = await Promise.all([\n    db\n      .from("lesson_instances")\n      .select(\n        "id,school_id,class_id,academic_year_id,lesson_date,slot_order,starts_at,ends_at,subject_name,title,topic,status,curriculum_subject_id,curriculum_topic_id,teacher_note",\n      )\n      .eq("class_id", classInfo.id)\n      .eq("lesson_date", nextDate)\n      .order("slot_order"),\n    db\n      .from("calendar_events")\n      .select("id,title,kind,starts_at,ends_at,all_day,blocks_lessons")\n      .eq("school_id", classInfo.school_id)\n      .lt("starts_at", tomorrowEnd)\n      .gt("ends_at", tomorrowStart)\n      .or(`class_id.eq.${classInfo.id},scope.eq.school,scope.eq.private`)\n      .order("starts_at"),\n    db\n      .from("system_calendar_days")\n      .select("title,kind,starts_on,ends_on,blocks_lessons")\n      .lte("starts_on", nextDate)\n      .gte("ends_on", nextDate),\n  ]);\n  for (const result of [tomorrowLessonsResult, tomorrowCalendarResult, tomorrowSystemResult])\n    if (result.error) throw result.error;\n\n  const tomorrowLessons = (tomorrowLessonsResult.data ?? []) as LessonInstance[];\n  const tomorrowLessonIds = tomorrowLessons.map((lesson) => lesson.id);\n  const [tomorrowPrepResult, tomorrowMaterialsResult] = await Promise.all([\n    tomorrowLessonIds.length\n      ? db.from("lesson_preparations").select("lesson_id").in("lesson_id", tomorrowLessonIds)\n      : Promise.resolve({ data: [], error: null }),\n    tomorrowLessonIds.length\n      ? db.from("lesson_materials").select("lesson_id,kind").in("lesson_id", tomorrowLessonIds)\n      : Promise.resolve({ data: [], error: null }),\n  ]);\n  if (tomorrowPrepResult.error) throw tomorrowPrepResult.error;\n  if (tomorrowMaterialsResult.error) throw tomorrowMaterialsResult.error;\n\n  const tomorrowPreparedIds = new Set(\n    (tomorrowPrepResult.data ?? []).map((row: any) => row.lesson_id as string),\n  );\n  const tomorrowWorksheetIds = new Set(\n    (tomorrowMaterialsResult.data ?? [])\n      .filter((row: any) => row.kind === "worksheet")\n      .map((row: any) => row.lesson_id as string),\n  );\n  const tomorrowBlockingEvents = [\n    ...(tomorrowCalendarResult.data ?? []),\n    ...(tomorrowSystemResult.data ?? []),\n  ].filter((event: any) => Boolean(event.blocks_lessons));\n  const tomorrowBlocked = tomorrowBlockingEvents.length > 0;\n\n'''
if marker not in text:
    raise SystemExit('events marker missing')
text = text.replace(marker, insert + marker, 1)

marker = '''  for (const carry of carryOvers.slice(0, 3))\n    recommendedActions.push({\n      id: `carry:${carry.lessonId}`,\n      priority: "medium",\n      title: `Navázat: ${carry.subject}`,\n      detail: carry.unfinished,\n      kind: "carry_over",\n      to: `/hodina/${carry.lessonId}`,\n      lessonId: carry.lessonId,\n    });\n\n'''
insert = '''  if (tomorrowBlocked) {\n    const blocker = tomorrowBlockingEvents[0] as any;\n    recommendedActions.push({\n      id: `tomorrow-blocked:${nextDate}`,\n      priority: "high",\n      title: "Zítřek má jiný režim",\n      detail: `${blocker?.title ?? "Školní událost"} blokuje běžnou výuku. Otevři kalendář a zkontroluj den.`,\n      kind: "tomorrow_blocker",\n      to: "/kalendar",\n    });\n  } else {\n    for (const lesson of tomorrowLessons) {\n      if (lesson.status === "cancelled") continue;\n      const prepared = tomorrowPreparedIds.has(lesson.id);\n      if (!prepared) {\n        recommendedActions.push({\n          id: `tomorrow-prep:${lesson.id}`,\n          priority: "medium",\n          title: `Zítra ještě připravit: ${lesson.subject_name}`,\n          detail: `${lesson.slot_order}. hodina · příprava zatím není uložená`,\n          kind: "tomorrow_prep",\n          to: `/hodina/${lesson.id}`,\n          lessonId: lesson.id,\n        });\n        continue;\n      }\n      if (!tomorrowWorksheetIds.has(lesson.id))\n        recommendedActions.push({\n          id: `tomorrow-worksheet:${lesson.id}`,\n          priority: "low",\n          title: `Pracovní list k ${lesson.subject_name}?`,\n          detail: "Příprava je hotová, ale pracovní list k ní zatím není uložený.",\n          kind: "tomorrow_worksheet",\n          to: `/hodina/${lesson.id}`,\n          lessonId: lesson.id,\n        });\n    }\n  }\n\n'''
if marker not in text:
    raise SystemExit('carry marker missing')
text = text.replace(marker, marker + insert, 1)

path.write_text(text)
