/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistentkaRouteImport } from './routes/asistentka'
import { Route as HlasRouteImport } from './routes/hlas'
import { Route as KalendarRouteImport } from './routes/kalendar'
import { Route as PametRouteImport } from './routes/pamet'
import { Route as RozvrhRouteImport } from './routes/rozvrh'
import { Route as SpecialniPedagogikaRouteImport } from './routes/specialni-pedagogika'
import { Route as TridaRouteImport } from './routes/trida'
import { Route as VytvarnaVychovaRouteImport } from './routes/vytvarna-vychova'
import { Route as ZacatekRouteImport } from './routes/zacatek'
import { Route as HodinaLessonIdRouteImport } from './routes/hodina.$lessonId'
import { Route as SpecialniPedagogikaCaseIdRouteImport } from './routes/specialni-pedagogika.$caseId'
import { Route as SpecialniPedagogikaCaseIdSouhrnRouteImport } from './routes/specialni-pedagogika.$caseId.souhrn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistentkaRoute = AsistentkaRouteImport.update({
  id: '/asistentka',
  path: '/asistentka',
  getParentRoute: () => rootRouteImport,
} as any)
const HlasRoute = HlasRouteImport.update({
  id: '/hlas',
  path: '/hlas',
  getParentRoute: () => rootRouteImport,
} as any)
const KalendarRoute = KalendarRouteImport.update({
  id: '/kalendar',
  path: '/kalendar',
  getParentRoute: () => rootRouteImport,
} as any)
const PametRoute = PametRouteImport.update({
  id: '/pamet',
  path: '/pamet',
  getParentRoute: () => rootRouteImport,
} as any)
const RozvrhRoute = RozvrhRouteImport.update({
  id: '/rozvrh',
  path: '/rozvrh',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialniPedagogikaRoute = SpecialniPedagogikaRouteImport.update({
  id: '/specialni-pedagogika',
  path: '/specialni-pedagogika',
  getParentRoute: () => rootRouteImport,
} as any)
const TridaRoute = TridaRouteImport.update({
  id: '/trida',
  path: '/trida',
  getParentRoute: () => rootRouteImport,
} as any)
const VytvarnaVychovaRoute = VytvarnaVychovaRouteImport.update({
  id: '/vytvarna-vychova',
  path: '/vytvarna-vychova',
  getParentRoute: () => rootRouteImport,
} as any)
const ZacatekRoute = ZacatekRouteImport.update({
  id: '/zacatek',
  path: '/zacatek',
  getParentRoute: () => rootRouteImport,
} as any)
const HodinaLessonIdRoute = HodinaLessonIdRouteImport.update({
  id: '/hodina/$lessonId',
  path: '/hodina/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialniPedagogikaCaseIdRoute =
  SpecialniPedagogikaCaseIdRouteImport.update({
    id: '/$caseId',
    path: '/$caseId',
    getParentRoute: () => SpecialniPedagogikaRoute,
  } as any)
const SpecialniPedagogikaCaseIdSouhrnRoute =
  SpecialniPedagogikaCaseIdSouhrnRouteImport.update({
    id: '/souhrn',
    path: '/souhrn',
    getParentRoute: () => SpecialniPedagogikaCaseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistentka': typeof AsistentkaRoute
  '/hlas': typeof HlasRoute
  '/kalendar': typeof KalendarRoute
  '/pamet': typeof PametRoute
  '/rozvrh': typeof RozvrhRoute
  '/specialni-pedagogika': typeof SpecialniPedagogikaRouteWithChildren
  '/trida': typeof TridaRoute
  '/vytvarna-vychova': typeof VytvarnaVychovaRoute
  '/zacatek': typeof ZacatekRoute
  '/hodina/$lessonId': typeof HodinaLessonIdRoute
  '/specialni-pedagogika/$caseId': typeof SpecialniPedagogikaCaseIdRouteWithChildren
  '/specialni-pedagogika/$caseId/souhrn': typeof SpecialniPedagogikaCaseIdSouhrnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistentka': typeof AsistentkaRoute
  '/hlas': typeof HlasRoute
  '/kalendar': typeof KalendarRoute
  '/pamet': typeof PametRoute
  '/rozvrh': typeof RozvrhRoute
  '/specialni-pedagogika': typeof SpecialniPedagogikaRouteWithChildren
  '/trida': typeof TridaRoute
  '/vytvarna-vychova': typeof VytvarnaVychovaRoute
  '/zacatek': typeof ZacatekRoute
  '/hodina/$lessonId': typeof HodinaLessonIdRoute
  '/specialni-pedagogika/$caseId': typeof SpecialniPedagogikaCaseIdRouteWithChildren
  '/specialni-pedagogika/$caseId/souhrn': typeof SpecialniPedagogikaCaseIdSouhrnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistentka': typeof AsistentkaRoute
  '/hlas': typeof HlasRoute
  '/kalendar': typeof KalendarRoute
  '/pamet': typeof PametRoute
  '/rozvrh': typeof RozvrhRoute
  '/specialni-pedagogika': typeof SpecialniPedagogikaRouteWithChildren
  '/trida': typeof TridaRoute
  '/vytvarna-vychova': typeof VytvarnaVychovaRoute
  '/zacatek': typeof ZacatekRoute
  '/hodina/$lessonId': typeof HodinaLessonIdRoute
  '/specialni-pedagogika/$caseId': typeof SpecialniPedagogikaCaseIdRouteWithChildren
  '/specialni-pedagogika/$caseId/souhrn': typeof SpecialniPedagogikaCaseIdSouhrnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asistentka'
    | '/hlas'
    | '/kalendar'
    | '/pamet'
    | '/rozvrh'
    | '/specialni-pedagogika'
    | '/trida'
    | '/vytvarna-vychova'
    | '/zacatek'
    | '/hodina/$lessonId'
    | '/specialni-pedagogika/$caseId'
    | '/specialni-pedagogika/$caseId/souhrn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asistentka'
    | '/hlas'
    | '/kalendar'
    | '/pamet'
    | '/rozvrh'
    | '/specialni-pedagogika'
    | '/trida'
    | '/vytvarna-vychova'
    | '/zacatek'
    | '/hodina/$lessonId'
    | '/specialni-pedagogika/$caseId'
    | '/specialni-pedagogika/$caseId/souhrn'
  id:
    | '__root__'
    | '/'
    | '/asistentka'
    | '/hlas'
    | '/kalendar'
    | '/pamet'
    | '/rozvrh'
    | '/specialni-pedagogika'
    | '/trida'
    | '/vytvarna-vychova'
    | '/zacatek'
    | '/hodina/$lessonId'
    | '/specialni-pedagogika/$caseId'
    | '/specialni-pedagogika/$caseId/souhrn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistentkaRoute: typeof AsistentkaRoute
  HlasRoute: typeof HlasRoute
  KalendarRoute: typeof KalendarRoute
  PametRoute: typeof PametRoute
  RozvrhRoute: typeof RozvrhRoute
  SpecialniPedagogikaRoute: typeof SpecialniPedagogikaRouteWithChildren
  TridaRoute: typeof TridaRoute
  VytvarnaVychovaRoute: typeof VytvarnaVychovaRoute
  ZacatekRoute: typeof ZacatekRoute
  HodinaLessonIdRoute: typeof HodinaLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistentka': {
      id: '/asistentka'
      path: '/asistentka'
      fullPath: '/asistentka'
      preLoaderRoute: typeof AsistentkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hlas': {
      id: '/hlas'
      path: '/hlas'
      fullPath: '/hlas'
      preLoaderRoute: typeof HlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalendar': {
      id: '/kalendar'
      path: '/kalendar'
      fullPath: '/kalendar'
      preLoaderRoute: typeof KalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pamet': {
      id: '/pamet'
      path: '/pamet'
      fullPath: '/pamet'
      preLoaderRoute: typeof PametRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rozvrh': {
      id: '/rozvrh'
      path: '/rozvrh'
      fullPath: '/rozvrh'
      preLoaderRoute: typeof RozvrhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialni-pedagogika': {
      id: '/specialni-pedagogika'
      path: '/specialni-pedagogika'
      fullPath: '/specialni-pedagogika'
      preLoaderRoute: typeof SpecialniPedagogikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trida': {
      id: '/trida'
      path: '/trida'
      fullPath: '/trida'
      preLoaderRoute: typeof TridaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vytvarna-vychova': {
      id: '/vytvarna-vychova'
      path: '/vytvarna-vychova'
      fullPath: '/vytvarna-vychova'
      preLoaderRoute: typeof VytvarnaVychovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zacatek': {
      id: '/zacatek'
      path: '/zacatek'
      fullPath: '/zacatek'
      preLoaderRoute: typeof ZacatekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hodina/$lessonId': {
      id: '/hodina/$lessonId'
      path: '/hodina/$lessonId'
      fullPath: '/hodina/$lessonId'
      preLoaderRoute: typeof HodinaLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialni-pedagogika/$caseId': {
      id: '/specialni-pedagogika/$caseId'
      path: '/$caseId'
      fullPath: '/specialni-pedagogika/$caseId'
      preLoaderRoute: typeof SpecialniPedagogikaCaseIdRouteImport
      parentRoute: typeof SpecialniPedagogikaRoute
    }
    '/specialni-pedagogika/$caseId/souhrn': {
      id: '/specialni-pedagogika/$caseId/souhrn'
      path: '/souhrn'
      fullPath: '/specialni-pedagogika/$caseId/souhrn'
      preLoaderRoute: typeof SpecialniPedagogikaCaseIdSouhrnRouteImport
      parentRoute: typeof SpecialniPedagogikaCaseIdRoute
    }
  }
}

interface SpecialniPedagogikaCaseIdRouteChildren {
  SpecialniPedagogikaCaseIdSouhrnRoute: typeof SpecialniPedagogikaCaseIdSouhrnRoute
}

const SpecialniPedagogikaCaseIdRouteChildren: SpecialniPedagogikaCaseIdRouteChildren =
  {
    SpecialniPedagogikaCaseIdSouhrnRoute: SpecialniPedagogikaCaseIdSouhrnRoute,
  }

const SpecialniPedagogikaCaseIdRouteWithChildren =
  SpecialniPedagogikaCaseIdRoute._addFileChildren(
    SpecialniPedagogikaCaseIdRouteChildren,
  )

interface SpecialniPedagogikaRouteChildren {
  SpecialniPedagogikaCaseIdRoute: typeof SpecialniPedagogikaCaseIdRouteWithChildren
}

const SpecialniPedagogikaRouteChildren: SpecialniPedagogikaRouteChildren = {
  SpecialniPedagogikaCaseIdRoute: SpecialniPedagogikaCaseIdRouteWithChildren,
}

const SpecialniPedagogikaRouteWithChildren =
  SpecialniPedagogikaRoute._addFileChildren(SpecialniPedagogikaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistentkaRoute: AsistentkaRoute,
  HlasRoute: HlasRoute,
  KalendarRoute: KalendarRoute,
  PametRoute: PametRoute,
  RozvrhRoute: RozvrhRoute,
  SpecialniPedagogikaRoute: SpecialniPedagogikaRouteWithChildren,
  TridaRoute: TridaRoute,
  VytvarnaVychovaRoute: VytvarnaVychovaRoute,
  ZacatekRoute: ZacatekRoute,
  HodinaLessonIdRoute: HodinaLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
