/* eslint-disable */
// @ts-nocheck
// This file is normally generated by TanStack Router. Kept in sync manually in this environment.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistentkaRouteImport } from './routes/asistentka'
import { Route as HodinaLessonIdRouteImport } from './routes/hodina.$lessonId'
import { Route as KalendarRouteImport } from './routes/kalendar'
import { Route as RozvrhRouteImport } from './routes/rozvrh'
import { Route as TridaRouteImport } from './routes/trida'
import { Route as ZacatekRouteImport } from './routes/zacatek'
import { Route as SpecialniPedagogikaRouteImport } from './routes/specialni-pedagogika'
const IndexRoute=IndexRouteImport.update({id:'/',path:'/',getParentRoute:()=>rootRouteImport} as any)
const AsistentkaRoute=AsistentkaRouteImport.update({id:'/asistentka',path:'/asistentka',getParentRoute:()=>rootRouteImport} as any)
const HodinaLessonIdRoute=HodinaLessonIdRouteImport.update({id:'/hodina/$lessonId',path:'/hodina/$lessonId',getParentRoute:()=>rootRouteImport} as any)
const KalendarRoute=KalendarRouteImport.update({id:'/kalendar',path:'/kalendar',getParentRoute:()=>rootRouteImport} as any)
const RozvrhRoute=RozvrhRouteImport.update({id:'/rozvrh',path:'/rozvrh',getParentRoute:()=>rootRouteImport} as any)
const TridaRoute=TridaRouteImport.update({id:'/trida',path:'/trida',getParentRoute:()=>rootRouteImport} as any)
const ZacatekRoute=ZacatekRouteImport.update({id:'/zacatek',path:'/zacatek',getParentRoute:()=>rootRouteImport} as any)
const SpecialniPedagogikaRoute=SpecialniPedagogikaRouteImport.update({id:'/specialni-pedagogika',path:'/specialni-pedagogika',getParentRoute:()=>rootRouteImport} as any)
export interface FileRoutesByFullPath {'/':typeof IndexRoute;'/asistentka':typeof AsistentkaRoute;'/hodina/$lessonId':typeof HodinaLessonIdRoute;'/kalendar':typeof KalendarRoute;'/rozvrh':typeof RozvrhRoute;'/trida':typeof TridaRoute;'/zacatek':typeof ZacatekRoute;'/specialni-pedagogika':typeof SpecialniPedagogikaRoute}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {__root__:typeof rootRouteImport;'/':typeof IndexRoute;'/asistentka':typeof AsistentkaRoute;'/hodina/$lessonId':typeof HodinaLessonIdRoute;'/kalendar':typeof KalendarRoute;'/rozvrh':typeof RozvrhRoute;'/trida':typeof TridaRoute;'/zacatek':typeof ZacatekRoute;'/specialni-pedagogika':typeof SpecialniPedagogikaRoute}
export interface FileRouteTypes {fileRoutesByFullPath:FileRoutesByFullPath;fullPaths:'/'|'/asistentka'|'/hodina/$lessonId'|'/kalendar'|'/rozvrh'|'/trida'|'/zacatek'|'/specialni-pedagogika';fileRoutesByTo:FileRoutesByTo;to:'/'|'/asistentka'|'/hodina/$lessonId'|'/kalendar'|'/rozvrh'|'/trida'|'/zacatek'|'/specialni-pedagogika';id:'__root__'|'/'|'/asistentka'|'/hodina/$lessonId'|'/kalendar'|'/rozvrh'|'/trida'|'/zacatek'|'/specialni-pedagogika';fileRoutesById:FileRoutesById}
export interface RootRouteChildren {IndexRoute:typeof IndexRoute;AsistentkaRoute:typeof AsistentkaRoute;HodinaLessonIdRoute:typeof HodinaLessonIdRoute;KalendarRoute:typeof KalendarRoute;RozvrhRoute:typeof RozvrhRoute;TridaRoute:typeof TridaRoute;ZacatekRoute:typeof ZacatekRoute;SpecialniPedagogikaRoute:typeof SpecialniPedagogikaRoute}
declare module '@tanstack/react-router' {interface FileRoutesByPath {'/':{id:'/';path:'/';fullPath:'/';preLoaderRoute:typeof IndexRouteImport;parentRoute:typeof rootRouteImport};'/asistentka':{id:'/asistentka';path:'/asistentka';fullPath:'/asistentka';preLoaderRoute:typeof AsistentkaRouteImport;parentRoute:typeof rootRouteImport};'/hodina/$lessonId':{id:'/hodina/$lessonId';path:'/hodina/$lessonId';fullPath:'/hodina/$lessonId';preLoaderRoute:typeof HodinaLessonIdRouteImport;parentRoute:typeof rootRouteImport};'/kalendar':{id:'/kalendar';path:'/kalendar';fullPath:'/kalendar';preLoaderRoute:typeof KalendarRouteImport;parentRoute:typeof rootRouteImport};'/rozvrh':{id:'/rozvrh';path:'/rozvrh';fullPath:'/rozvrh';preLoaderRoute:typeof RozvrhRouteImport;parentRoute:typeof rootRouteImport};'/trida':{id:'/trida';path:'/trida';fullPath:'/trida';preLoaderRoute:typeof TridaRouteImport;parentRoute:typeof rootRouteImport};'/zacatek':{id:'/zacatek';path:'/zacatek';fullPath:'/zacatek';preLoaderRoute:typeof ZacatekRouteImport;parentRoute:typeof rootRouteImport};'/specialni-pedagogika':{id:'/specialni-pedagogika';path:'/specialni-pedagogika';fullPath:'/specialni-pedagogika';preLoaderRoute:typeof SpecialniPedagogikaRouteImport;parentRoute:typeof rootRouteImport}}}
const rootRouteChildren:RootRouteChildren={IndexRoute,AsistentkaRoute,HodinaLessonIdRoute,KalendarRoute,RozvrhRoute,TridaRoute,ZacatekRoute,SpecialniPedagogikaRoute}
export const routeTree=rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {interface Register {ssr:true;router:Awaited<ReturnType<typeof getRouter>>;config:Awaited<ReturnType<typeof startInstance.getOptions>>}}
