-- Intentionally retained as a no-op migration.
--
-- Lovable generated this migration after the same assistant-coordinator slice
-- had already been committed in 20260829231500_assistant_coordinator_slice.sql.
-- Keeping this timestamped migration avoids rewriting migration history while
-- ensuring local resets and future production pushes have one authoritative
-- schema definition for this slice.
--
-- Authoritative migration:
--   20260829231500_assistant_coordinator_slice.sql
