-- Intentionally retained as a no-op migration.
--
-- Lovable generated this migration after the same schema change had already been
-- committed in 20260829160000_teacher_personal_important_dates.sql. Keeping the
-- timestamped file preserves migration-history compatibility, while making a
-- from-empty reset safe and preventing the duplicate CHECK constraints from
-- being created twice.
--
-- Authoritative migration:
--   20260829160000_teacher_personal_important_dates.sql
