-- Intentionally retained as a no-op migration.
--
-- Lovable generated this migration after the same schema change had already been
-- committed in 20260829193500_special_education_external_documentation.sql.
-- Keeping the timestamped file preserves migration-history compatibility and
-- prevents duplicate RLS policies / schema objects during a from-empty reset.
--
-- Authoritative migration:
--   20260829193500_special_education_external_documentation.sql
